name: Binary Builds Pre-Releases

on:
  push:
    tags:
      - 'v*-dev.*'

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Generate Change Log
        id: generate_log
        run: |
          go get github.com/barelyhuman/commitlog
          commitlog > CHANGELOG.txt
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: "linux/amd64, linux/arm, linux/arm64, darwin/amd64"
          package: ""
          name: statico
          compress: "true"
          dest: dist
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.txt
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
